# Generated by Django 6.0.2 on 2026-02-05 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in kilometers', max_digits=10)),
                ('reason', models.CharField(max_length=255)),
                ('fuel_type', models.CharField(max_length=50)),
                ('cost_per_liter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_quantity', models.DecimalField(decimal_places=2, help_text='Total liters', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_fuel_type', models.CharField(default='Petrol', max_length=50)),
                ('default_cost_per_liter', models.DecimalField(decimal_places=2, default=1.5, max_digits=10)),
            ],
        ),
    ]
