# Generated by Django 6.0.2 on 2026-02-06 10:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Fuel Name')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, help_text='Current cost per unit (e.g. per liter)', max_digits=5, verbose_name='Cost per Unit')),
                ('unit_name', models.CharField(default='Liters', help_text='Unit of measurement (e.g. Liters, Gallons, kWh)', max_length=20, verbose_name='Unit Name')),
                ('efficiency', models.DecimalField(decimal_places=2, default=15.0, help_text='Average Distance per Unit (e.g. km/L)', max_digits=6, verbose_name='Efficiency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fuel Type',
                'verbose_name_plural': 'Fuel Types',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Car Name')),
                ('make', models.CharField(blank=True, max_length=50, verbose_name='Make')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='Model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
                ('fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.fueltype', verbose_name='Default Fuel Type')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in kilometers', max_digits=10, verbose_name='Distance')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason')),
                ('fuel_type', models.CharField(max_length=50, verbose_name='Fuel Type Name')),
                ('cost_per_liter', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost per Unit')),
                ('fuel_quantity', models.DecimalField(decimal_places=2, help_text='Total units (e.g. liters)', max_digits=10, verbose_name='Fuel Quantity')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Cost')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.car', verbose_name='Car')),
                ('fuel_type_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.fueltype', verbose_name='Fuel Type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journey',
                'verbose_name_plural': 'Journeys',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='$', help_text='Currency symbol (e.g. $, €, £)', max_length=5, verbose_name='Currency')),
                ('language', models.CharField(choices=[('en', 'English'), ('it', 'Italian')], default='en', max_length=2, verbose_name='Language')),
                ('default_fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.fueltype', verbose_name='Default Fuel Type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.AddConstraint(
            model_name='fueltype',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_fuel_type_per_user'),
        ),
    ]
