# Generated by Django 6.0.2 on 2026-02-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='language',
        ),
    ]
