# Generated by Django 6.0.2 on 2026-02-05 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, help_text='Current cost per unit (e.g. per liter)', max_digits=5)),
                ('unit_name', models.CharField(default='Liters', help_text='Unit of measurement (e.g. Liters, Gallons, kWh)', max_length=20)),
                ('efficiency', models.DecimalField(decimal_places=2, default=15.0, help_text='Average Distance per Unit (e.g. km/L)', max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='settings',
            name='default_cost_per_liter',
        ),
        migrations.AddField(
            model_name='settings',
            name='currency',
            field=models.CharField(default='$', help_text='Currency symbol (e.g. $, €, £)', max_length=5),
        ),
        migrations.AlterField(
            model_name='journey',
            name='cost_per_liter',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost per Unit'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='fuel_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Total units (e.g. liters)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='journey',
            name='fuel_type',
            field=models.CharField(max_length=50, verbose_name='Fuel Type Name'),
        ),
        migrations.AddField(
            model_name='journey',
            name='fuel_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.fueltype', verbose_name='Fuel Type'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.fueltype'),
        ),
    ]
